#!/bin/bash

set -Eeu
source $lib/dsinfo

HELP_TXT=$(cat <<EOF
Copy or move annex objects into a 7z archive, accessible by ria-remote
EOF
)
SUBCOMMANDS=$(cat <<EOF
move - move objects into the 7z archive
copy - copy objects into to the archive, without deleting the originals
EOF
)

# from PATH, need not be executable

params=$(parse_args "$@")

action=$(get 1 "$params")
if [ "$action" = "move" ]; then
  move=1
elif [ "$action" = "copy" ]; then
  move=0
else
  >&2 echo "First argument must be 'move' or 'copy'; got '$action'"
  exit 1
fi
# take off mode arg and find dataset with the rest

set_active_ds $(get 2- "$params")

# uncompressed archive by default
sevenzopts=${HP_ZIPOPTS:--mx0}

objpath="$(get_active_ds path)/annex/objects"
archivepath="$(get_active_ds path)/archives"

if [ ! -d "$objpath" ]; then
  >&2 echo "No annex objects. Done."
  exit 0
fi

if [ ! -d "$archivepath" ]; then
    mkdir -p "$archivepath"
    # only chown when freshly created to not destroy potential
    # custom permission setup
    # whoever owns the object store, owns the archives
    chown -R --reference "$objpath" "$archivepath"
fi

if [ $move = 1 ]; then
  mv "$objpath" "$objpath"_
  objpath="$objpath"_
fi

cd "$objpath"
# always update, also works from scratch
7z u "$archivepath/archive.7z" . $sevenzopts
chown -R --reference "$objpath" "$archivepath"/archive.7z
cd -

if [ $move = 1 ]; then
  rm -rf "$objpath"
  rmdir --ignore-fail-on-non-empty "$ds_path/annex"
fi
