#!/bin/bash
set -Eeu
source $lib/dsinfo

HELP_TXT=$(cat <<EOF
Print dataset IDs for each subdataset recorded in a dataset

Subdataset not available in the same datastore are reported via stderr and result in a
non-zero exit code.
EOF
)

set_active_ds $(parse_args "$@")

error=0
if git_ds cat-file -e HEAD:.gitmodules 2>/dev/null; then
  for dep in $(git_ds cat-file -p HEAD:.gitmodules | grep '^\sdatalad-id' | cut -d= -f2); do
    dep_path="$(get_active_ds base)/$(id2relpath "$dep")"
    if [ ! -d "$dep_path" ]; then
      >&2 echo "$dep" not available in "$(get_active_ds base)"
      error=1
    else
      echo "$dep"
    fi
  done
fi

exit $error
