#!/bin/bash
set -Eeu
source $lib/dsinfo

HELP_TXT=$(cat <<EOF
Clean up and minimize a dataset
EOF
)

args=$(parse_args "$@")
try_set_active_ds "$args"


if ! is_active; then
  find "$1" \
      -mindepth 3 -maxdepth 3 \
      -name objects \
      -type d \
      -print \
      -execdir $bin/gc \;
  exit 0
fi

# all local operations
pushd $(get_active_ds path)

# run garbage collection
git gc --aggressive

# fixup ownership of files created by GC when ran as root
chown --changes -R --from=root --reference=config refs packed-refs

# delete sample hooks
if [ -d hooks ]; then
  rm -f hooks/*.sample
  rmdir --ignore-fail-on-non-empty hooks
fi
# delete branches/ and refs/tags/ if empty
[ -d branches ] && rmdir --ignore-fail-on-non-empty branches || true
[ -d refs/tags ] && rmdir -p --ignore-fail-on-non-empty refs/tags || true

# delete template "unnamed" repo description
[ "$(cat description 2>/dev/null | cut -d ";" -f1,1)"x = "Unnamed repository"x ] && rm description || true

popd