#!/bin/bash
set -Eeu

source $lib/dsinfo
HELP_TXT=$(cat <<EOF
Print the timestamp and user ID of the last dataset update

When called any standard dataset argument, reports information for that single dataset.

When called with the location of an entire datastore, reports this information for all
datasets in it. Each line additionally reports the path to the dataset in the store
EOF
)

try_set_active_ds "$@"

if is_active; then
  git_ds rev-list HEAD -n 1 --format="format:%aI %aE" | tail -n1
else
  find "$1" \
      -mindepth 3 -maxdepth 3 \
      -name objects \
      -type d \
      -execdir bash -c 'printf "$(git rev-list HEAD -n 1 --format="format:%aI %aE" | tail -n1)\t$(readlink -f .)\n"' \;
fi
