#!/bin/bash

set -e -u

HELP_TXT=$(cat <<EOF
Report any dataset item not containing a Git repo
EOF
)

for i in $(find -H "$1" -mindepth 2 -maxdepth 2); do
    test -d "$i"/objects && true || echo "$i";
done

